# Generated by Django 4.1.1 on 2022-10-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_doctor_alter_visit_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
