# Generated by Django 4.1.1 on 2022-10-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_visit_doctor_delete_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.IntegerField(),
        ),
    ]
