# Generated by Django 4.1.1 on 2022-10-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_visit_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='time',
        ),
        migrations.AddField(
            model_name='visit',
            name='hours',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='visit',
            name='minutes',
            field=models.IntegerField(default=8),
        ),
    ]
