# Generated by Django 4.1.1 on 2022-10-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_visit_time_visit_hours_visit_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='minutes',
        ),
    ]
