# Generated by Django 4.1.1 on 2022-10-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_visit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('desc', models.TextField()),
                ('spec', models.TextField()),
                ('pesel', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=100)),
                ('addr_number', models.CharField(max_length=100)),
            ],
        ),
    ]
