# Generated by Django 4.1.1 on 2022-10-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pesel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spec',
            field=models.TextField(default=''),
        ),
    ]
