# Generated by Django 4.1.1 on 2022-10-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile_tel_alter_profile_desc_alter_profile_pesel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='addr_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
